# -*- coding: utf-8 -*-
"""basic weather app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eZtZsAqCuNo1HBLGZzuIK6DY-JZpCd-q
"""

pip install requests

import requests

def get_weather(api_key, location):
    url = f"http://api.openweathermap.org/data/2.5/weather?q={location}&appid={api_key}&units=metric"
    response = requests.get(url)

    if response.status_code == 200:
        data = response.json()
        temp = data['main']['temp']
        humidity = data['main']['humidity']
        description = data['weather'][0]['description']

        print(f"Weather in {location.capitalize()}:")
        print(f"Temperature: {temp}°C")
        print(f"Humidity: {humidity}%")
        print(f"Condition: {description.capitalize()}")
    else:
        print("Error fetching weather data. Please check the location or API key.")
        print(response.json())

def main():
    api_key = "your_valid_api_key_here"  # Replace with your actual API key
    location = input("Enter city name: ")
    get_weather(api_key, location)

if __name__ == "__main__":
    main()